@extends('layouts.mahasiswa')
@section('title', 'Tugas & Kuis | SALE')
@section('header', 'Tugas & Kuis')
@section('content')
<div class="space-y-6"><header><h1 class="page-heading">Tugas & Kuis</h1><p class="page-description">Rekap pekerjaan dari semua course. Materi dan diskusi tetap ada di kelasnya.</p></header>
<nav aria-label="Tampilan tugas" class="flex gap-6  text-sm font-semibold"><a href="{{ route('mahasiswa.assignment.index') }}" class="border-b-2 pb-3 {{ request('tab') !== 'nilai' ? 'border-brand text-brand' : 'border-transparent text-muted' }}">Semua pekerjaan</a><a href="{{ route('mahasiswa.assignment.index', ['tab'=>'nilai']) }}" class="border-b-2 pb-3 {{ request('tab') === 'nilai' ? 'border-brand text-brand' : 'border-transparent text-muted' }}">Nilai & umpan balik</a></nav>
<form class="flex flex-wrap gap-3" method="get"><input type="hidden" name="tab" value="{{ request('tab') }}"><label class="sr-only" for="q">Cari tugas</label><input id="q" name="q" class="field sm:w-64" value="{{ request('q') }}" placeholder="Cari tugas atau kuis"><label class="sr-only" for="course">Course</label><select id="course" name="course" class="field sm:w-60"><option value="">Semua course</option>@foreach($courses as $course)<option value="{{ $course['id'] }}" @selected(request('course') == $course['id'])>{{ $course['code'] }} · {{ $course['title'] }}</option>@endforeach</select><label class="sr-only" for="type">Jenis</label><select id="type" name="type" class="field sm:w-44"><option value="">Semua jenis</option>@foreach(['tugas'=>'Tugas','coding'=>'Tugas coding','kuis'=>'Kuis'] as $value=>$label)<option value="{{ $value }}" @selected(request('type') === $value)>{{ $label }}</option>@endforeach</select><button class="button-secondary">Terapkan</button></form>
@if(request('tab') === 'nilai')<p class="text-sm text-muted">Nilai dan umpan balik muncul setelah dosen menilai. Nilai akhir belum tersedia.</p>@endif
<section class="surface space-y-2">@forelse($items as $item)<a href="{{ route('mahasiswa.course.item', [$item['course'], $item['id']]) }}" class="flex flex-wrap items-center justify-between gap-4 p-5 hover:bg-brand-soft/40"><div><p class="text-xs font-semibold text-brand">{{ $courses[$item['course']]['code'] }} · {{ \App\Support\LearningPreview::labels()[$item['type']] }}</p><h2 class="mt-2 font-semibold">{{ $item['title'] }}</h2><p class="mt-1 text-sm text-muted">{{ $item['module'] }}</p></div><div class="text-sm sm:text-right"><p class="font-medium">{{ request('tab') === 'nilai' ? 'Belum dinilai' : (session('learning.submissions.'.$item['id']) ? 'Sudah dikumpulkan' : 'Belum dikumpulkan') }}</p><p class="mt-1 text-xs text-muted">{{ $item['due'] ? \Carbon\Carbon::parse($item['due'])->translatedFormat('d M Y, H:i') : 'Tanpa tenggat' }} →</p></div></a>@empty<div class="p-8"><h2 class="section-heading">Tidak ada pekerjaan yang cocok</h2><p class="mt-2 text-sm text-muted">Ubah filter untuk melihat pekerjaan lainnya.</p></div>@endforelse</section></div>
@endsection
