@extends('layouts.mahasiswa')
@section('title', $item['title'].' | SALE')
@section('header', $course['title'])
@section('content')
<div class="space-y-6">
<nav class="flex flex-wrap gap-2 text-sm text-muted" aria-label="Breadcrumb"><a class="quiet-link" href="{{ route('mahasiswa.course.index') }}">Course</a><span>/</span><a class="quiet-link" href="{{ route('mahasiswa.course.show', $course['id']) }}">{{ $course['code'] }}</a><span>/ {{ $item['module'] }}</span></nav>
<header><span class="status">{{ \App\Support\LearningPreview::labels()[$item['type']] }}</span><h1 class="page-heading mt-3">{{ $item['title'] }}</h1><p class="page-description">{{ $course['lecturer'] }} · {{ $item['module'] }}</p></header>
<div class="grid items-start gap-7 xl:grid-cols-[minmax(0,1fr)_340px]">
<div class="min-w-0 space-y-6">
<section class="surface p-6 sm:p-7"><h2 class="section-heading">{{ $item['type'] === 'materi' ? 'Materi pembelajaran' : 'Petunjuk' }}</h2><p class="prose-content mt-4 text-sm">{{ $item['body'] }}</p>
@if($item['attachments'] || $item['link'])<h3 class="mt-7 text-sm font-semibold">Lampiran</h3><div class="mt-3 space-y-2">@foreach($item['attachments'] as $file)<a class="flex items-center justify-between gap-3 rounded-lg border border-line p-4 text-sm hover:bg-canvas" href="{{ route('preview.file', $file) }}" target="_blank" rel="noopener"><span class="break-all">{{ session('learning.files.'.$file.'.name', 'Berkas materi') }}</span><span>↗</span></a>@endforeach @if($item['link'])<a class="quiet-link block break-all py-2" href="{{ $item['link'] }}" target="_blank" rel="noopener noreferrer">{{ $item['link'] }} ↗</a>@endif</div>@endif
<details class="mt-6 border-t border-line pt-4"><summary class="cursor-pointer text-sm font-semibold">Capaian pembelajaran</summary><p class="mt-3 text-sm text-muted">{{ $item['cpmk'] }}</p></details></section>
<section id="diskusi" class="surface scroll-mt-24 p-6 sm:p-7"><h2 class="section-heading">Diskusi modul</h2><p class="mt-1 text-sm text-muted">Percakapan khusus untuk {{ $item['title'] }}.</p>
<div class="my-6 space-y-5">@forelse(session('learning.discussions.'.$item['id'], []) as $message)<article class="border-b border-line pb-5"><div class="flex items-center gap-3"><span class="flex h-8 w-8 items-center justify-center rounded-full bg-brand-soft text-xs font-semibold text-brand">AM</span><h3 class="text-sm font-semibold">{{ $message['author'] }}</h3><span class="text-xs text-muted">{{ $message['time'] }}</span></div><p class="prose-content mt-3 text-sm">{{ $message['message'] }}</p></article>@empty<p class="rounded-lg bg-canvas p-5 text-sm text-muted">Belum ada diskusi. Mulai dengan pertanyaan tentang materi atau instruksi di atas.</p>@endforelse</div>
<form method="post" action="{{ route('mahasiswa.course.discuss', [$course['id'], $item['id']]) }}">@csrf<label class="form-label" for="message">Tulis pertanyaan atau tanggapan</label><textarea required maxlength="3000" name="message" id="message" rows="3" class="field" placeholder="Bagian mana yang ingin kamu diskusikan?">{{ old('message') }}</textarea><div class="mt-3 flex items-center justify-between gap-4"><p class="text-xs text-muted">Percakapan pratinjau tersimpan di sesi ini.</p><button class="button-primary">Kirim</button></div></form></section>
</div>
<aside class="surface p-6">
@if(in_array($item['type'], ['tugas','coding','kuis']))
<h2 class="section-heading">Pekerjaan kamu</h2><p class="mt-2 text-sm text-muted">{{ $item['due'] ? 'Tenggat '.\Carbon\Carbon::parse($item['due'])->translatedFormat('d M Y, H:i') : 'Tanpa tenggat' }}</p>
@php($submission = session('learning.submissions.'.$item['id']))
@if($submission)<div role="status" class="my-5 rounded-lg bg-brand-soft p-4 text-sm"><p class="font-semibold text-brand">Sudah dikumpulkan</p><p class="mt-1">{{ $submission['time'] }}</p><p class="mt-2 text-muted">Menunggu penilaian dosen.</p></div>@if(!empty($submission['answer']))<details class="my-4 text-sm"><summary class="cursor-pointer font-semibold">Lihat jawaban</summary><p class="prose-content mt-2">{{ $submission['answer'] }}</p></details>@endif @foreach($submission['files'] as $file)<a class="quiet-link my-3 block break-all" href="{{ route('preview.file', $file) }}">{{ session('learning.files.'.$file.'.name') }}</a>@endforeach @if(!empty($submission['link']))<a class="quiet-link my-3 block break-all" href="{{ $submission['link'] }}" target="_blank" rel="noopener noreferrer">{{ $submission['link'] }} ↗</a>@endif @if(!empty($submission['choices']))<p class="my-3 text-sm">Pilihan: {{ implode('; ', $submission['choices']) }}</p>@endif
@else<p class="my-5 text-sm font-medium">Belum dikumpulkan</p>@endif
@if($item['type'] === 'coding')<a class="button-primary mt-2 w-full" href="{{ route('mahasiswa.assignment.code', $item['id']) }}">Buka ruang koding →</a>
@else
<form class="mt-5 space-y-4" method="post" enctype="multipart/form-data" action="{{ route('mahasiswa.course.submit', [$course['id'], $item['id']]) }}">@csrf
@if(in_array($item['question_type'], ['pilihan','kompleks']))<fieldset><legend class="form-label">{{ $item['question_type'] === 'kompleks' ? 'Pilih semua jawaban yang sesuai' : 'Pilih satu jawaban' }}</legend>@foreach(array_filter(array_map('trim', explode("\n", $item['options'] ?? ''))) as $option)<label class="my-2 flex gap-3 rounded-lg border border-line p-3 text-sm"><input type="{{ $item['question_type'] === 'kompleks' ? 'checkbox' : 'radio' }}" name="choices[]" value="{{ $option }}">{{ $option }}</label>@endforeach</fieldset>@endif
@if(in_array('text',$item['formats']) || $item['type'] === 'coding')<div><label class="form-label" for="answer">{{ $item['type'] === 'coding' ? 'Kode jawaban' : 'Jawaban / catatan' }}</label><textarea id="answer" name="answer" rows="5" class="field">{{ old('answer', $submission['answer'] ?? '') }}</textarea></div>@endif
@if(in_array('file',$item['formats']) || in_array('image',$item['formats']))<div><label class="form-label" for="files">Lampiran jawaban</label><input id="files" name="files[]" type="file" multiple data-file-input class="field text-sm" accept="{{ in_array('file',$item['formats']) ? '.pdf,.doc,.docx,.ppt,.pptx,.zip,' : '' }}{{ in_array('image',$item['formats']) ? '.jpg,.jpeg,.png,.webp' : '' }}"><p class="mt-2 text-xs text-muted">Maks. 5 berkas, 20 MB per berkas. {{ in_array('file',$item['formats']) ? 'PDF, Word, PowerPoint, ZIP.' : '' }} {{ in_array('image',$item['formats']) ? 'JPG, PNG, WebP.' : '' }}</p><p data-file-list class="mt-2 break-all text-xs text-muted"></p></div>@endif
@if(in_array('link',$item['formats']))<div><label class="form-label" for="link">Tautan jawaban</label><input type="url" id="link" name="link" class="field" placeholder="https://" value="{{ old('link', $submission['link'] ?? '') }}"></div>@endif
<button class="button-primary w-full">{{ $submission ? 'Kumpulkan ulang' : 'Kumpulkan jawaban' }}</button><p class="text-xs leading-5 text-muted">Pengumpulan pratinjau disimpan pada sesi browser ini.</p></form>@endif
@else<h2 class="section-heading">Tentang materi ini</h2><p class="mt-3 text-sm leading-6 text-muted">Pelajari materi dan lampiran dari dosen. Gunakan diskusi di bawah materi untuk bertanya kepada kelas.</p><a class="button-secondary mt-5 w-full" href="#diskusi">Buka diskusi</a>@endif
</aside>
</div>
</div>
@endsection
