@extends('layouts.mahasiswa')
@section('header', 'Tambah course')
@section('content')
<div class="mx-auto max-w-3xl"><a class="quiet-link" href="{{ route('dosen.course.index') }}">← Course saya</a><h1 class="page-heading mt-5">Tambah course</h1><p class="page-description">Siapkan identitas kelas. Materi dan tugas ditambahkan setelah course dibuat.</p>
<form method="post" enctype="multipart/form-data" action="{{ route('dosen.course.store') }}" class="surface mt-7 space-y-6 p-6 sm:p-8">@csrf
<div><label class="form-label" for="cover">Gambar sampul <span class="font-normal text-muted">(opsional)</span></label><div class="rounded-lg border border-dashed border-line bg-canvas p-5"><img data-cover-preview hidden alt="Pratinjau sampul" class="mb-4 h-40 w-full rounded-lg object-cover"><input class="field" id="cover" name="cover" type="file" accept="image/jpeg,image/png,image/webp" data-cover-input><p class="mt-2 text-xs text-muted">JPG, PNG, atau WebP. Maksimal 5 MB. Gunakan gambar lebar, misalnya 1600 × 600 px.</p><button type="button" data-cover-remove class="quiet-link mt-3" hidden>Hapus gambar</button></div></div>
<div class="grid gap-5 sm:grid-cols-[140px_1fr]"><div><label class="form-label" for="code">Kode course</label><input required maxlength="20" class="field" name="code" id="code" value="{{ old('code') }}" placeholder="IF204"></div><div><label class="form-label" for="title">Nama course</label><input required maxlength="120" class="field" name="title" id="title" value="{{ old('title') }}" placeholder="Struktur Data dan Algoritma"></div></div>
<div><label class="form-label" for="lecturer">Dosen pengampu</label><input required class="field" name="lecturer" id="lecturer" value="{{ old('lecturer', 'Dr. Budi Santoso, M.Kom.') }}"></div>
<div><label class="form-label" for="description">Deskripsi singkat</label><textarea required maxlength="2000" class="field" rows="4" name="description" id="description">{{ old('description') }}</textarea></div>
<div><label class="form-label" for="video">Tautan video pengantar <span class="font-normal text-muted">(opsional)</span></label><input class="field" type="url" name="video" id="video" value="{{ old('video') }}" placeholder="https://"><p class="mt-2 text-xs text-muted">Ditampilkan di bagian atas course.</p></div>
<div class="flex items-center justify-between  pt-5"><a class="button-secondary" href="{{ route('dosen.course.index') }}">Batal</a><button class="button-primary">Buat course</button></div><p class="text-xs text-muted">Course pratinjau tersimpan di sesi ini. Penetapan peserta oleh admin belum dihubungkan.</p></form></div>
@endsection
