@extends('layouts.mahasiswa')
@section('header', 'Tambah konten course')
@section('content')
<div class="mx-auto max-w-3xl"><a class="quiet-link" href="{{ route('dosen.course.show', $course['id']) }}">← {{ $course['title'] }}</a><h1 class="page-heading mt-5">Tambah konten</h1><p class="page-description">Materi, tugas, dan pengumuman tetap terhubung ke course ini.</p>
<form class="surface mt-7 space-y-6 p-6 sm:p-8" action="{{ route('dosen.item.store', $course['id']) }}" method="post" enctype="multipart/form-data">@csrf
<div class="grid gap-5 sm:grid-cols-2"><div><label class="form-label" for="type">Jenis konten</label><select id="type" name="type" class="field" data-content-type>@foreach(\App\Support\LearningPreview::labels() as $value=>$label)<option value="{{ $value }}" @selected(old('type') === $value)>{{ $label }}</option>@endforeach</select></div><div><label class="form-label" for="module">Nama modul / topik</label><input id="module" name="module" class="field" required maxlength="100" list="modules" value="{{ old('module') }}" placeholder="Minggu 3 · Tree dan traversal"><datalist id="modules">@foreach(collect(\App\Support\LearningPreview::items())->where('course', $course['id'])->pluck('module')->unique() as $module)<option value="{{ $module }}">@endforeach</datalist></div></div>
<div><label class="form-label" for="title">Judul</label><input id="title" name="title" required maxlength="160" class="field" value="{{ old('title') }}"></div>
<div><label class="form-label" for="body">Materi / instruksi / stimulus soal</label><textarea id="body" name="body" required rows="6" class="field">{{ old('body') }}</textarea></div>
<section class="rounded-xl bg-canvas p-5"><div class="flex items-start justify-between gap-3"><div><h2 class="font-semibold">Gambar pada soal / materi</h2><p class="mt-1 text-xs leading-5 text-muted">Tambahkan diagram, tabel, ilustrasi, atau stimulus visual. Gambar tampil langsung di atas jawaban.</p></div></div><div class="mt-4"><input id="question_image" name="question_image" type="file" accept="image/jpeg,image/png,image/webp" data-image-input class="field" aria-label="Gambar soal"><img data-image-preview hidden alt="Pratinjau gambar soal" class="mt-4 max-h-64 rounded-lg object-contain"><button data-image-remove type="button" hidden class="quiet-link mt-3">Hapus gambar soal</button></div><label class="form-label mt-4" for="image_alt">Deskripsi gambar</label><input id="image_alt" name="image_alt" class="field" maxlength="300" placeholder="Jelaskan isi gambar untuk mahasiswa yang memakai pembaca layar" value="{{ old('image_alt') }}"><p class="mt-2 text-xs text-muted">JPG, PNG, atau WebP, maksimal 5 MB. Deskripsi wajib ketika gambar diunggah.</p></section>
<div><label class="form-label" for="attachments">Lampiran materi atau gambar soal</label><input id="attachments" name="attachments[]" type="file" multiple data-file-input class="field" accept=".pdf,.ppt,.pptx,.doc,.docx,.jpg,.jpeg,.png,.webp,.mp4"><p class="mt-2 text-xs text-muted">PDF, PowerPoint, Word, gambar, atau MP4. Maksimal 5 berkas, 20 MB per berkas.</p><div data-file-list class="mt-3 space-y-2"></div></div>
<div><label class="form-label" for="link">Tautan materi / video (opsional)</label><input id="link" name="link" type="url" class="field" value="{{ old('link') }}" placeholder="https://"></div>
<div data-assignment-fields class="space-y-5  pt-5"><h2 class="section-heading">Pengaturan pekerjaan</h2><div class="grid gap-5 sm:grid-cols-2"><div><label class="form-label" for="question_type">Bentuk soal</label><select id="question_type" name="question_type" class="field" data-question-type>@foreach(['uraian'=>'Uraian / jawaban terbuka','pilihan'=>'AKM · Pilihan ganda','kompleks'=>'AKM · Pilihan ganda kompleks','coding'=>'Pemrograman'] as $value=>$label)<option value="{{ $value }}" @selected(old('question_type') === $value)>{{ $label }}</option>@endforeach</select></div><div><label class="form-label" for="due">Tenggat (opsional)</label><input type="datetime-local" id="due" name="due" class="field" value="{{ old('due') }}"></div></div>
<div data-choice-fields><label class="form-label" for="options">Pilihan jawaban</label><textarea id="options" name="options" rows="4" class="field" placeholder="Satu pilihan per baris">{{ old('options') }}</textarea><p class="mt-2 text-xs text-muted">Minimal dua pilihan. Penilaian dilakukan dosen; kunci otomatis belum tersedia.</p><div data-option-images class="mt-4 space-y-3"></div><p class="mt-2 text-xs text-muted">Setiap pilihan dapat dilengkapi gambar JPG, PNG, atau WebP (maks. 2 MB). Teks pilihan juga menjadi deskripsi gambarnya.</p></div>
<div><label class="form-label" for="points">Poin maksimal</label><input type="number" id="points" name="points" min="1" max="1000" class="field max-w-40" value="{{ old('points',100) }}"></div><fieldset><legend class="form-label">Format jawaban yang diterima</legend><div class="flex flex-wrap gap-4">@foreach(['file'=>'Dokumen / ZIP','image'=>'Gambar','link'=>'Tautan','text'=>'Teks'] as $value=>$label)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="formats[]" value="{{ $value }}" @checked(in_array($value, old('formats', ['file','image','link','text'])))>{{ $label }}</label>@endforeach</div></fieldset></div>
<div><label class="form-label" for="cpmk">Capaian pembelajaran / CPMK</label><textarea required id="cpmk" name="cpmk" rows="2" class="field" placeholder="Mahasiswa mampu…">{{ old('cpmk') }}</textarea></div>
<div class="flex justify-between  pt-5"><a class="button-secondary" href="{{ route('dosen.course.show', $course['id']) }}">Batal</a><button class="button-primary">Tambahkan ke course</button></div></form></div>
@endsection
