@extends('layouts.mahasiswa')
@section('header','Pengguna & hak akses')
@section('content')
<div class="space-y-6"><header class="flex flex-wrap items-end justify-between gap-4"><div><h1 class="page-heading">Pengguna & hak akses</h1><p class="page-description">Atur identitas, peran, dan status akun institusi.</p></div><a class="button-primary" href="{{ route('admin.page','pengguna') }}?create=1">+ Tambah pengguna</a></header>
@if(request('create') || $record || $errors->any())
<form class="surface space-y-5 p-6" method="post" action="{{ route('admin.users.store') }}">@csrf @if($record)<input type="hidden" name="id" value="{{ $record['id'] }}">@endif<h2 class="section-heading">{{ $record ? 'Edit pengguna' : 'Pengguna baru' }}</h2><div class="grid gap-5 md:grid-cols-2">@foreach(['name'=>'Nama lengkap','email'=>'Email','number'=>'NIM / NIDN / nomor pegawai'] as $key=>$label)<div><label class="form-label" for="{{ $key }}">{{ $label }}</label><input class="field" id="{{ $key }}" name="{{ $key }}" type="{{ $key === 'email' ? 'email' : 'text' }}" required value="{{ old($key,$record[$key] ?? '') }}"></div>@endforeach<div><label class="form-label" for="role">Peran</label><select class="field" id="role" name="role">@foreach(['mahasiswa'=>'Mahasiswa','dosen'=>'Dosen','admin'=>'Administrator'] as $key=>$label)<option value="{{ $key }}" @selected(old('role',$record['role'] ?? '')===$key)>{{ $label }}</option>@endforeach</select></div><div><label class="form-label" for="status">Status</label><select class="field" id="status" name="status">@foreach(['aktif'=>'Aktif','nonaktif'=>'Nonaktif'] as $key=>$label)<option value="{{ $key }}" @selected(old('status',$record['status'] ?? '')===$key)>{{ $label }}</option>@endforeach</select></div></div><p class="text-xs text-muted">Perubahan peran dicatat pada activity log. Undangan akun dan login belum diaktifkan.</p><div class="flex gap-3"><button class="button-primary">Simpan pengguna</button><a class="button-secondary" href="{{ route('admin.page','pengguna') }}">Batal</a></div></form>
@endif
<form class="flex flex-wrap gap-3"><label class="sr-only" for="q">Cari pengguna</label><input class="field sm:w-72" id="q" name="q" placeholder="Cari nama, email, atau nomor" value="{{ request('q') }}"><label class="sr-only" for="role-filter">Filter peran</label><select class="field sm:w-48" id="role-filter" name="role"><option value="">Semua peran</option>@foreach(['mahasiswa','dosen','admin'] as $role)<option @selected(request('role')===$role)>{{ $role }}</option>@endforeach</select><button class="button-secondary">Cari</button></form>
<div class="surface overflow-x-auto"><table class="admin-table"><thead><tr><th>Nama & identitas</th><th>Email</th><th>Peran</th><th>Status</th><th><span class="sr-only">Aksi</span></th></tr></thead><tbody>@forelse($visibleUsers as $user)<tr><td><p class="font-semibold">{{ $user['name'] }}</p><p class="mt-1 text-xs text-muted">{{ $user['number'] }}</p></td><td>{{ $user['email'] }}</td><td>{{ ucfirst($user['role']) }}</td><td>{{ ucfirst($user['status']) }}</td><td><a class="quiet-link" href="{{ route('admin.page','pengguna') }}?edit={{ $user['id'] }}">Edit<span class="sr-only"> {{ $user['name'] }}</span></a></td></tr>@empty<tr><td colspan="5">Pengguna tidak ditemukan.</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
