@extends('layouts.mahasiswa')
@section('title', 'Dashboard | SALE')
@section('header', 'Dashboard')
@section('content')
<div class="space-y-7"><header><p class="eyebrow mb-2">Semester ganjil 2026/2027</p><h1 class="page-heading">Selamat datang, Ahmad.</h1><p class="page-description">Mulai dari course kamu, lalu lihat pekerjaan yang perlu diselesaikan.</p></header>
<section class="flex flex-wrap items-center justify-between gap-5 rounded-xl bg-brand-dark p-6 text-white sm:p-8"><div><p class="text-xs font-medium text-white/80">Pilihan materi · IF204</p><h2 class="mt-2 text-xl font-semibold">Memahami traversal pada Binary Tree</h2><p class="mt-2 max-w-xl text-sm leading-6 text-white/80">Pelajari urutan kunjungan simpul sebelum melanjutkan praktikum.</p></div><a href="{{ route('mahasiswa.course.item', [1,3]) }}" class="button-secondary">Buka materi →</a></section>
<div class="grid items-start gap-7 xl:grid-cols-[minmax(0,1fr)_300px]"><section><div class="mb-4 flex items-center justify-between"><h2 class="section-heading">Course kamu</h2><a class="quiet-link" href="{{ route('mahasiswa.course.index') }}">Lihat semua</a></div><div class="grid gap-4 md:grid-cols-2">@foreach(\App\Support\LearningPreview::courses() as $course)<a class="surface overflow-hidden hover:border-brand" href="{{ route('mahasiswa.course.show', $course['id']) }}">@if($course['cover'])<img class="h-24 w-full object-cover" alt="Sampul course" src="{{ route('preview.file',$course['cover']) }}">@else<div class="bg-brand-dark px-5 py-5 font-mono text-lg text-white">{{ $course['code'] }}</div>@endif<div class="p-5"><h3 class="font-semibold">{{ $course['title'] }}</h3><p class="mt-2 text-xs text-muted">{{ $course['lecturer'] }}</p><p class="mt-5 text-sm font-medium text-brand">Buka kelas →</p></div></a>@endforeach</div></section>
<aside class="space-y-5"><section class="surface p-5"><h2 class="section-heading">Pekerjaan berikutnya</h2><div class="mt-3 divide-y divide-line">@forelse(collect(\App\Support\LearningPreview::items())->whereIn('type',['tugas','coding','kuis'])->filter(fn($i)=>!session('learning.submissions.'.$i['id']))->sortBy('due')->take(3) as $item)<a class="block py-4" href="{{ route('mahasiswa.course.item',[$item['course'],$item['id']]) }}"><p class="text-xs text-muted">{{ $item['due'] ? \Carbon\Carbon::parse($item['due'])->translatedFormat('d M, H:i') : 'Tanpa tenggat' }}</p><h3 class="mt-1 text-sm font-semibold">{{ $item['title'] }}</h3></a>@empty<p class="py-4 text-sm text-muted">Semua pekerjaan sudah dikumpulkan.</p>@endforelse</div><a class="quiet-link" href="{{ route('mahasiswa.assignment.index') }}">Semua tugas & kuis →</a></section><section class="surface p-5"><h2 class="font-semibold">Aktivitas belajar</h2><p class="mt-3 text-sm text-muted">{{ count(session('learning.submissions', [])) }} pekerjaan dikumpulkan dalam sesi ini.</p><p class="mt-3 text-xs leading-5 text-muted">XP, badge, dan rekomendasi personal tersedia setelah pencatatan aktivitas terhubung.</p></section></aside></div></div>
@endsection
