<?php

namespace App\Http\Controllers\AdminProdi;

use App\Models\Prodi;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Illuminate\View\View;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\HttpFoundation\StreamedResponse;

class UserProdiController extends AdminProdiController
{
    public function index(Request $request): View
    {
        $prodis = $this->allowedProdis();
        $activeProdi = $this->resolveActiveProdi($request);

        $tab = $request->query('tab', 'dosen');

        $dosens = User::query()
            ->withRoleName(Role::DOSEN)
            ->when($activeProdi, fn ($q) => $q->where(function ($sub) use ($activeProdi) {
                $sub->where('prodi_id', $activeProdi->id)->orWhere('managing_prodi_id', $activeProdi->id);
            }))
            ->with('prodi')
            ->orderBy('name')
            ->get();

        $mahasiswas = User::query()
            ->withRoleName(Role::MAHASISWA)
            ->when($activeProdi, fn ($q) => $q->where(function ($sub) use ($activeProdi) {
                $sub->where('prodi_id', $activeProdi->id);
            }))
            ->with('prodi')
            ->orderBy('nim_nidn')
            ->paginate(25)
            ->withQueryString();

        return view('admin-prodi.users.index', compact(
            'prodis',
            'activeProdi',
            'tab',
            'dosens',
            'mahasiswas'
        ));
    }

    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'role_type' => ['required', Rule::in(['dosen', 'mahasiswa'])],
        ]);

        $roleType = $request->input('role_type');
        $roleName = $roleType === 'dosen' ? Role::DOSEN : Role::MAHASISWA;
        $role = Role::where('name', $roleName)->firstOrFail();

        $idLabel = $roleType === 'dosen' ? 'NIDN / NIP' : 'NIM';

        $validated = $request->validate([
            'name' => ['required', 'string', 'max:150'],
            'email' => ['required', 'string', 'email', 'max:150', 'unique:users,email'],
            'nim_nidn' => ['required', 'string', 'max:30', 'unique:users,nim_nidn'],
            'prodi_id' => ['required', 'exists:prodis,id'],
            'password' => ['nullable', 'string', 'min:8', 'max:255'],
        ], [
            'nim_nidn.required' => "{$idLabel} wajib diisi.",
            'nim_nidn.unique' => "{$idLabel} sudah terdaftar.",
            'email.unique' => 'Email sudah terdaftar pada sistem.',
        ]);

        // Pastikan admin hanya bisa menambah user ke prodinya sendiri
        $this->assertProdiScope($validated['prodi_id']);

        // Gunakan password yang diberikan atau buat password sementara acak.
        // Semua akun baru wajib mengganti kredensial yang diketahui admin saat login pertama.
        $autoGenerated = empty($validated['password']);
        $password = $autoGenerated
            ? Str::password(16)
            : $validated['password'];

        $user = User::create([
            'name' => trim($validated['name']),
            'email' => strtolower(trim($validated['email'])),
            'nim_nidn' => trim($validated['nim_nidn']),
            'prodi_id' => $validated['prodi_id'],
            'role_id' => $role->id,
            'password' => Hash::make($password),
            'must_change_password' => true,
            'email_verified_at' => now(),
        ]);

        $label = $roleType === 'dosen' ? 'Dosen' : 'Mahasiswa';
        $notice = "Data {$label} \"{$validated['name']}\" berhasil ditambahkan.";
        if ($autoGenerated) {
            $notice .= " Password sementara: {$password} (wajib diganti saat login pertama)";
        }

        return redirect()->route('admin-prodi.users.index', ['prodi_id' => $validated['prodi_id'], 'tab' => $roleType])
            ->with('notice', $notice);
    }

    public function update(Request $request, User $user): RedirectResponse
    {
        $this->assertUserScope($user);
        $roleType = $user->hasRole(Role::DOSEN) ? 'dosen' : 'mahasiswa';
        $idLabel = $roleType === 'dosen' ? 'NIDN / NIP' : 'NIM';

        $validated = $request->validate([
            'name' => ['required', 'string', 'max:150'],
            'email' => ['required', 'string', 'email', 'max:150', Rule::unique('users', 'email')->ignore($user->id)],
            'nim_nidn' => ['required', 'string', 'max:30', Rule::unique('users', 'nim_nidn')->ignore($user->id)],
            'prodi_id' => ['required', 'exists:prodis,id'],
            'password' => ['nullable', 'string', 'min:8', 'max:255'],
        ], [
            'nim_nidn.unique' => "{$idLabel} sudah terdaftar.",
            'email.unique' => 'Email sudah terdaftar.',
        ]);

        $this->assertProdiScope((int) $validated['prodi_id']);

        $updateData = [
            'name' => trim($validated['name']),
            'email' => strtolower(trim($validated['email'])),
            'nim_nidn' => trim($validated['nim_nidn']),
            'prodi_id' => $validated['prodi_id'],
        ];

        if (! empty($validated['password'])) {
            $updateData['password'] = Hash::make($validated['password']);
            $updateData['must_change_password'] = true;
        }

        $user->update($updateData);

        return redirect()->route('admin-prodi.users.index', ['prodi_id' => $validated['prodi_id'], 'tab' => $roleType])
            ->with('notice', "Data pengguna \"{$user->name}\" berhasil diperbarui.");
    }

    public function destroy(User $user): RedirectResponse
    {
        $this->assertUserScope($user);
        $roleType = $user->hasRole(Role::DOSEN) ? 'dosen' : 'mahasiswa';
        $name = $user->name;
        $prodiId = $user->prodi_id;

        if ($user->classSectionsTeaching()->exists() || $user->classSectionsEnrolled()->exists()) {
            return back()->withErrors([
                'user' => "Pengguna {$name} tidak dapat dihapus karena sudah memiliki keterkaitan dengan kelas perkuliahan aktif.",
            ]);
        }

        $user->delete();

        return redirect()->route('admin-prodi.users.index', ['prodi_id' => $prodiId, 'tab' => $roleType])
            ->with('notice', "Pengguna {$name} berhasil dihapus.");
    }

    public function downloadTemplate(string $type): StreamedResponse
    {
        $type = in_array($type, ['dosen', 'mahasiswa']) ? $type : 'mahasiswa';
        $fileName = "template-import-{$type}.xlsx";

        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Template Import');

        if ($type === 'dosen') {
            $headers = ['NIDN_NIP', 'Nama Lengkap', 'Email Institusi', 'Password'];
            $samples = [
                ['198502022010121002', 'Dr. Hendra Wijaya, M.Kom.', 'hendra@example.test', ''],
                ['199003032015042001', 'Nurul Hidayah, S.Kom., M.T.', 'nurul@example.test', ''],
            ];
        } else {
            $headers = ['NIM', 'Nama Mahasiswa', 'Email Mahasiswa', 'Password'];
            $samples = [
                ['231011409001', 'Muhammad Zaky Pratama', 'zaky@student.test', ''],
                ['231011409002', 'Aisyah Putri Rahmadhani', 'aisyah@student.test', ''],
            ];
        }

        $sheet->fromArray([$headers], null, 'A1');
        $sheet->getStyle('A1:D1')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['rgb' => '4472C4'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
        ]);
        $sheet->getRowDimension(1)->setRowHeight(24);

        $row = 2;
        foreach ($samples as $sample) {
            $sheet->fromArray([$sample], null, "A{$row}");
            // Nomor NIM/NIDN sebagai teks agar tidak dipotong
            $sheet->getCell("A{$row}")->setValueExplicit($sample[0], \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);
            $sheet->getRowDimension($row)->setRowHeight(20);
            $row++;
        }

        $lastRow = $row - 1;
        $sheet->getStyle("A1:D{$lastRow}")->applyFromArray([
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['rgb' => 'D1D5DB'],
                ],
            ],
        ]);

        foreach (['A', 'B', 'C', 'D'] as $col) {
            $sheet->getColumnDimension($col)->setAutoSize(true);
        }

        return response()->streamDownload(function () use ($spreadsheet) {
            $writer = new Xlsx($spreadsheet);
            $writer->save('php://output');
        }, $fileName, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => "attachment; filename=\"{$fileName}\"",
            'Cache-Control' => 'max-age=0',
        ]);
    }

    public function import(Request $request): RedirectResponse
    {
        $request->validate([
            'prodi_id' => ['required', 'exists:prodis,id'],
            'role_type' => ['required', Rule::in(['dosen', 'mahasiswa'])],
            'file' => ['required', 'file', 'mimes:csv,txt,xlsx,xls', 'max:4096'],
        ], [
            'file.required' => 'Pilih file Excel yang akan diimpor.',
            'file.mimes' => 'File yang diunggah harus berformat Excel (.xlsx, .xls) atau CSV.',
        ]);

        $prodiId = $request->integer('prodi_id');

        // Pastikan admin hanya bisa import ke prodinya sendiri
        $this->assertProdiScope($prodiId);
        $roleType = $request->input('role_type');
        $roleName = $roleType === 'dosen' ? Role::DOSEN : Role::MAHASISWA;
        $role = Role::where('name', $roleName)->firstOrFail();

        $uploadedFile = $request->file('file');
        $extension = strtolower($uploadedFile->getClientOriginalExtension());

        // Parsing baris data: support xlsx/xls dan csv/txt
        $rows = [];
        if (in_array($extension, ['xlsx', 'xls'])) {
            $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($uploadedFile->getRealPath());
            $sheet = $spreadsheet->getActiveSheet();
            foreach ($sheet->getRowIterator(2) as $row) {
                $cellIter = $row->getCellIterator();
                $cellIter->setIterateOnlyExistingCells(false);
                $cols = [];
                foreach ($cellIter as $cell) {
                    $cols[] = trim((string) $cell->getValue());
                }
                if (array_filter($cols) === []) {
                    continue;
                }
                $rows[] = $cols;
            }
        } else {
            $raw = file_get_contents($uploadedFile->getRealPath());
            $clean = preg_replace('/^\xEF\xBB\xBF/', '', $raw);
            $lines = preg_split('/\r\n|\r|\n/', trim($clean));
            if (! empty($lines) && count($lines) >= 2) {
                $headerLine = $lines[0];
                $delimiter = str_contains($headerLine, "\t") ? "\t" : (str_contains($headerLine, ';') ? ';' : ',');
                for ($i = 1; $i < count($lines); $i++) {
                    $line = trim($lines[$i]);
                    if ($line === '' || str_starts_with($line, '#')) {
                        continue;
                    }
                    $rows[] = array_map('trim', str_getcsv($line, $delimiter, '"', '\\'));
                }
            }
        }

        if (empty($rows)) {
            return back()->withErrors(['file' => 'File Excel kosong atau tidak berisi baris data.']);
        }

        $successCount = 0;
        $skippedCount = 0;
        $errors = [];
        $temporaryCredentials = [];

        DB::transaction(function () use ($rows, $prodiId, $role, &$successCount, &$skippedCount, &$errors, &$temporaryCredentials) {
            foreach ($rows as $idx => $cols) {
                $rowNum = $idx + 2; // +2: baris 1 adalah header, index 0 = baris data ke-2

                $idNum = isset($cols[0]) ? trim($cols[0], "'\"\t\n\r\0\x0B ") : '';
                $name  = isset($cols[1]) ? trim($cols[1], "'\"\t\n\r\0\x0B ") : '';
                $email = isset($cols[2]) ? trim($cols[2], "'\"\t\n\r\0\x0B ") : '';
                $pass  = (isset($cols[3]) && trim($cols[3]) !== '') ? trim($cols[3]) : null;

                if ($idNum === '' || $name === '' || $email === '') {
                    $skippedCount++;
                    $errors[] = "Baris {$rowNum}: Kolom nomor identitas, nama, atau email tidak boleh kosong.";

                    continue;
                }

                if (! filter_var($email, FILTER_VALIDATE_EMAIL)) {
                    $skippedCount++;
                    $errors[] = "Baris {$rowNum}: Format email '{$email}' tidak valid.";

                    continue;
                }

                if ($pass !== null && strlen($pass) < 8) {
                    $skippedCount++;
                    $errors[] = "Baris {$rowNum}: Password harus minimal 8 karakter jika diisi.";

                    continue;
                }

                $autoGenerated = ($pass === null);
                $pass = $autoGenerated ? Str::password(16) : $pass;

                $exists = User::where('email', strtolower($email))
                    ->orWhere('nim_nidn', $idNum)
                    ->exists();

                if ($exists) {
                    $skippedCount++;
                    $errors[] = "Baris {$rowNum}: Nomor '{$idNum}' atau email '{$email}' sudah terdaftar dalam sistem.";

                    continue;
                }

                User::create([
                    'name'                 => $name,
                    'email'                => strtolower($email),
                    'nim_nidn'             => $idNum,
                    'prodi_id'             => $prodiId,
                    'role_id'              => $role->id,
                    'password'             => Hash::make($pass),
                    'must_change_password' => true,
                    'email_verified_at'    => now(),
                ]);

                if ($autoGenerated) {
                    $temporaryCredentials[] = [
                        'identity' => $idNum,
                        'email'    => strtolower($email),
                        'password' => $pass,
                    ];
                }

                $successCount++;
            }
        });
        $typeLabel = $roleType === 'dosen' ? 'Dosen' : 'Mahasiswa';
        $msg = "Impor data {$typeLabel} selesai: {$successCount} berhasil ditambahkan.";
        if ($skippedCount > 0) {
            $msg .= " ({$skippedCount} baris diabaikan/duplikat).";
        }

        return redirect()->route('admin-prodi.users.index', ['prodi_id' => $prodiId, 'tab' => $roleType])
            ->with('notice', $msg)
            ->with('import_errors', $errors)
            ->with('temporary_credentials', $temporaryCredentials);
    }

    private function assertManageableUser(User $user): void
    {
        // Metode ini dipertahankan untuk kompatibilitas;
        // gunakan assertUserScope() untuk pengecekan lengkap dengan scope prodi.
        abort_unless(
            $user->hasRole(Role::DOSEN) || $user->hasRole(Role::MAHASISWA),
            404,
            'Pengguna tidak termasuk lingkup pengelolaan Admin Program Studi.'
        );
    }
}
