<?php

namespace App\Http\Controllers\AdminProdi;

use App\Models\Prodi;
use App\Models\Role;
use App\Models\Semester;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use Illuminate\View\View;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\HttpFoundation\StreamedResponse;

class UserProdiController extends AdminProdiController
{
    public function index(Request $request): View
    {
        $prodis = $this->allowedProdis();
        $activeProdi = $this->resolveActiveProdi($request);

        $tab = $request->query('tab', 'dosen');

        $dosens = $activeProdi
            ? User::query()
                ->withRoleName(Role::DOSEN)
                ->where(function ($sub) use ($activeProdi) {
                    $sub->where('prodi_id', $activeProdi->id)->orWhere('managing_prodi_id', $activeProdi->id);
                })
                ->with('prodi')
                ->orderBy('name')
                ->get()
            : collect();

        $mahasiswas = $activeProdi
            ? User::query()
                ->withRoleName(Role::MAHASISWA)
                ->where(function ($sub) use ($activeProdi) {
                    $sub->where('prodi_id', $activeProdi->id);
                })
                ->with('prodi')
                ->orderBy('nim_nidn')
                ->paginate(25)
                ->withQueryString()
            : new LengthAwarePaginator([], 0, 25);

        return view('admin-prodi.users.index', compact(
            'prodis',
            'activeProdi',
            'tab',
            'dosens',
            'mahasiswas'
        ));
    }

    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'role_type' => ['required', Rule::in(['dosen', 'mahasiswa'])],
        ]);

        $roleType = $request->input('role_type');
        $roleName = $roleType === 'dosen' ? Role::DOSEN : Role::MAHASISWA;
        $role = Role::where('name', $roleName)->firstOrFail();

        $idLabel = $roleType === 'dosen' ? 'NIDN / NIP' : 'NIM';

        $validated = $request->validate([
            'name' => ['required', 'string', 'max:150'],
            'email' => ['required', 'string', 'email', 'max:150', 'unique:users,email'],
            'nim_nidn' => ['required', 'string', 'max:30', 'unique:users,nim_nidn'],
            'angkatan' => ['nullable', 'integer', 'min:2000', 'max:2099'],
            'prodi_id' => ['required', 'exists:prodis,id'],
            'password' => ['nullable', 'string', 'min:8', 'max:255'],
        ], [
            'nim_nidn.required' => "{$idLabel} wajib diisi.",
            'nim_nidn.unique' => "{$idLabel} sudah terdaftar.",
            'email.unique' => 'Email sudah terdaftar pada sistem.',
        ]);

        // Pastikan admin hanya bisa menambah user ke prodinya sendiri
        $this->assertProdiScope($validated['prodi_id']);

        // Auto-detect angkatan untuk mahasiswa jika tidak diisi manual
        $angkatan = $validated['angkatan'] ?? null;
        if (! $angkatan && $roleType === 'mahasiswa') {
            $nim = trim($validated['nim_nidn']);
            if (preg_match('/^(20\d{2})/', $nim, $matches)) {
                $angkatan = (int) $matches[1];
            } elseif (preg_match('/^(\d{2})/', $nim, $matches)) {
                $two = (int) $matches[1];
                if ($two >= 18 && $two <= 35) {
                    $angkatan = 2000 + $two;
                }
            }
            if (! $angkatan) {
                $activeSem = Semester::where('is_active', true)->first();
                if ($activeSem && ! empty($activeSem->academic_year)) {
                    $angkatan = (int) explode('/', $activeSem->academic_year)[0];
                } else {
                    $angkatan = (int) date('Y');
                }
            }
        }

        // Gunakan password yang diberikan atau buat password otomatis berdasarkan NIM/NIP.
        // Semua akun baru wajib mengganti kredensial saat login pertama.
        $autoGenerated = empty($validated['password']);
        $password = $autoGenerated
            ? trim($validated['nim_nidn'])
            : $validated['password'];

        $user = User::create([
            'name' => trim($validated['name']),
            'email' => strtolower(trim($validated['email'])),
            'nim_nidn' => trim($validated['nim_nidn']),
            'angkatan' => $angkatan,
            'prodi_id' => $validated['prodi_id'],
            'role_id' => $role->id,
            'password' => Hash::make($password),
            'must_change_password' => true,
            'email_verified_at' => now(),
        ]);
        $user->roles()->sync([$role->id]);

        $label = $roleType === 'dosen' ? 'Dosen' : 'Mahasiswa';
        $notice = "Data {$label} \"{$validated['name']}\" berhasil ditambahkan.";
        if ($autoGenerated) {
            $notice .= " Password default: {$password} (sesuai {$idLabel}, wajib diganti saat login pertama)";
        }

        return redirect()->route('admin-prodi.users.index', ['prodi_id' => $validated['prodi_id'], 'tab' => $roleType])
            ->with('notice', $notice);
    }

    public function update(Request $request, User $user): RedirectResponse
    {
        $this->assertUserScope($user);
        $roleType = $user->hasRole(Role::DOSEN) ? 'dosen' : 'mahasiswa';
        $idLabel = $roleType === 'dosen' ? 'NIDN / NIP' : 'NIM';

        $validated = $request->validate([
            'name' => ['required', 'string', 'max:150'],
            'email' => ['required', 'string', 'email', 'max:150', Rule::unique('users', 'email')->ignore($user->id)],
            'nim_nidn' => ['required', 'string', 'max:30', Rule::unique('users', 'nim_nidn')->ignore($user->id)],
            'angkatan' => ['nullable', 'integer', 'min:2000', 'max:2099'],
            'prodi_id' => ['required', 'exists:prodis,id'],
            'password' => ['nullable', 'string', 'min:8', 'max:255'],
        ], [
            'nim_nidn.unique' => "{$idLabel} sudah terdaftar.",
            'email.unique' => 'Email sudah terdaftar.',
        ]);

        $this->assertProdiScope((int) $validated['prodi_id']);

        $updateData = [
            'name' => trim($validated['name']),
            'email' => strtolower(trim($validated['email'])),
            'nim_nidn' => trim($validated['nim_nidn']),
            'prodi_id' => $validated['prodi_id'],
        ];

        if ($request->has('angkatan')) {
            $updateData['angkatan'] = $request->input('angkatan') ?: null;
        }

        if (! empty($validated['password'])) {
            $updateData['password'] = Hash::make($validated['password']);
            $updateData['must_change_password'] = true;
        }

        $user->update($updateData);

        return redirect()->route('admin-prodi.users.index', ['prodi_id' => $validated['prodi_id'], 'tab' => $roleType])
            ->with('notice', "Data pengguna \"{$user->name}\" berhasil diperbarui.");
    }

    public function destroy(User $user): RedirectResponse
    {
        $this->assertUserScope($user);
        $roleType = $user->hasRole(Role::DOSEN) ? 'dosen' : 'mahasiswa';
        $name = $user->name;
        $prodiId = $user->prodi_id;

        if ($user->classSectionsTeaching()->exists() || $user->classSectionEnrollmentRecords()->exists()) {
            return back()->withErrors([
                'user' => "Pengguna {$name} tidak dapat dihapus karena sudah memiliki keterkaitan dengan kelas perkuliahan aktif.",
            ]);
        }

        $user->delete();

        return redirect()->route('admin-prodi.users.index', ['prodi_id' => $prodiId, 'tab' => $roleType])
            ->with('notice', "Pengguna {$name} berhasil dihapus.");
    }

    public function export(Request $request): StreamedResponse
    {
        $activeProdi = $this->resolveActiveProdi($request);
        $prodiId = $activeProdi?->id;

        $dosens = User::query()
            ->withRoleName(Role::DOSEN)
            ->when($prodiId, fn ($q) => $q->where(fn ($sub) => $sub->where('prodi_id', $prodiId)->orWhere('managing_prodi_id', $prodiId)))
            ->with('prodi')
            ->orderBy('name')
            ->get();

        $mahasiswas = User::query()
            ->withRoleName(Role::MAHASISWA)
            ->when($prodiId, fn ($q) => $q->where('prodi_id', $prodiId))
            ->with('prodi')
            ->orderBy('nim_nidn')
            ->get();

        $spreadsheet = new Spreadsheet;

        $borderThin = ['borderStyle' => Border::BORDER_THIN, 'color' => ['argb' => 'FF000000']];
        $borderMedium = ['borderStyle' => Border::BORDER_MEDIUM, 'color' => ['argb' => 'FF000000']];

        // ── Sheet 1: Data Dosen ──────────────────────────────────────────────
        $sheetDosen = $spreadsheet->getActiveSheet();
        $sheetDosen->setTitle('Data Dosen');

        $prodiTitle = $activeProdi ? "PROGRAM STUDI {$activeProdi->name} ({$activeProdi->code})" : 'SEMUA PROGRAM STUDI';
        $sheetDosen->setCellValue('A1', "DATA DOSEN PENGAMPU - {$prodiTitle}");
        $sheetDosen->mergeCells('A1:F1');
        $sheetDosen->getStyle('A1')->applyFromArray([
            'font' => ['bold' => true, 'size' => 12, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '15803D']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'borders' => ['outline' => $borderMedium],
        ]);
        $sheetDosen->getRowDimension(1)->setRowHeight(26);

        $sheetDosen->setCellValue('A2', 'Tanggal Ekspor: '.now()->translatedFormat('d F Y, H:i'));
        $sheetDosen->mergeCells('A2:F2');
        $sheetDosen->getStyle('A2:F2')->applyFromArray([
            'font' => ['size' => 10, 'italic' => true],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'F1F5F9']],
            'borders' => ['allBorders' => $borderThin],
        ]);
        $sheetDosen->getRowDimension(2)->setRowHeight(18);

        $dosenHeaders = ['No', 'NIDN / NIP', 'Nama Lengkap & Gelar', 'Email Institusi', 'Program Studi', 'Status Akun'];
        $cols = ['A', 'B', 'C', 'D', 'E', 'F'];
        foreach ($dosenHeaders as $k => $head) {
            $sheetDosen->setCellValue($cols[$k].'4', $head);
        }
        $sheetDosen->getStyle('A4:F4')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '15803D']],
            'borders' => ['allBorders' => $borderThin, 'outline' => $borderMedium],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);
        $sheetDosen->getRowDimension(4)->setRowHeight(22);
        $sheetDosen->freezePane('A5');

        $rowD = 5;
        foreach ($dosens as $i => $d) {
            $sheetDosen->setCellValue('A'.$rowD, $i + 1);
            $sheetDosen->setCellValueExplicit('B'.$rowD, $d->nim_nidn ?? '-', DataType::TYPE_STRING);
            $sheetDosen->setCellValue('C'.$rowD, $d->name);
            $sheetDosen->setCellValue('D'.$rowD, $d->email);
            $sheetDosen->setCellValue('E'.$rowD, $d->prodi?->name ?? 'Semua / Lintas Prodi');
            $sheetDosen->setCellValue('F'.$rowD, $d->is_active ? 'Aktif' : 'Nonaktif');

            $sheetDosen->getStyle("A{$rowD}:F{$rowD}")->applyFromArray([
                'borders' => ['allBorders' => $borderThin],
                'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
            ]);
            $sheetDosen->getStyle("A{$rowD}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheetDosen->getStyle("B{$rowD}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheetDosen->getStyle("F{$rowD}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheetDosen->getRowDimension($rowD)->setRowHeight(20);
            $rowD++;
        }

        $colWidthsDosen = [6, 22, 32, 30, 26, 14];
        foreach ($cols as $k => $col) {
            $sheetDosen->getColumnDimension($col)->setWidth($colWidthsDosen[$k]);
        }

        // ── Sheet 2: Data Mahasiswa ──────────────────────────────────────────
        $sheetMhs = $spreadsheet->createSheet();
        $sheetMhs->setTitle('Data Mahasiswa');

        $sheetMhs->setCellValue('A1', "DATA MAHASISWA - {$prodiTitle}");
        $sheetMhs->mergeCells('A1:G1');
        $sheetMhs->getStyle('A1')->applyFromArray([
            'font' => ['bold' => true, 'size' => 12, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '15803D']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'borders' => ['outline' => $borderMedium],
        ]);
        $sheetMhs->getRowDimension(1)->setRowHeight(26);

        $sheetMhs->setCellValue('A2', 'Tanggal Ekspor: '.now()->translatedFormat('d F Y, H:i'));
        $sheetMhs->mergeCells('A2:G2');
        $sheetMhs->getStyle('A2:G2')->applyFromArray([
            'font' => ['size' => 10, 'italic' => true],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'F1F5F9']],
            'borders' => ['allBorders' => $borderThin],
        ]);
        $sheetMhs->getRowDimension(2)->setRowHeight(18);

        $mhsHeaders = ['No', 'NIM', 'Nama Mahasiswa', 'Email Mahasiswa', 'Program Studi', 'Angkatan', 'Status Akun'];
        $colsMhs = ['A', 'B', 'C', 'D', 'E', 'F', 'G'];
        foreach ($mhsHeaders as $k => $head) {
            $sheetMhs->setCellValue($colsMhs[$k].'4', $head);
        }
        $sheetMhs->getStyle('A4:G4')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '15803D']],
            'borders' => ['allBorders' => $borderThin, 'outline' => $borderMedium],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);
        $sheetMhs->getRowDimension(4)->setRowHeight(22);
        $sheetMhs->freezePane('A5');

        $rowM = 5;
        foreach ($mahasiswas as $i => $m) {
            $sheetMhs->setCellValue('A'.$rowM, $i + 1);
            $sheetMhs->setCellValueExplicit('B'.$rowM, $m->nim_nidn ?? '-', DataType::TYPE_STRING);
            $sheetMhs->setCellValue('C'.$rowM, $m->name);
            $sheetMhs->setCellValue('D'.$rowM, $m->email);
            $sheetMhs->setCellValue('E'.$rowM, $m->prodi?->name ?? '-');
            $sheetMhs->setCellValue('F'.$rowM, $m->angkatan ?? '-');
            $sheetMhs->setCellValue('G'.$rowM, $m->is_active ? 'Aktif' : 'Nonaktif');

            $sheetMhs->getStyle("A{$rowM}:G{$rowM}")->applyFromArray([
                'borders' => ['allBorders' => $borderThin],
                'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
            ]);
            $sheetMhs->getStyle("A{$rowM}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheetMhs->getStyle("B{$rowM}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheetMhs->getStyle("F{$rowM}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheetMhs->getStyle("G{$rowM}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheetMhs->getRowDimension($rowM)->setRowHeight(20);
            $rowM++;
        }

        $colWidthsMhs = [6, 20, 32, 30, 26, 12, 14];
        foreach ($colsMhs as $k => $col) {
            $sheetMhs->getColumnDimension($col)->setWidth($colWidthsMhs[$k]);
        }

        $spreadsheet->setActiveSheetIndex(0);

        $safeProdi = preg_replace('/[^a-zA-Z0-9_\-]/', '_', $activeProdi?->code ?? 'SEMUA');
        $fileName = "data-pengguna-{$safeProdi}-".date('Ymd_His').'.xlsx';

        return response()->streamDownload(function () use ($spreadsheet) {
            $writer = new Xlsx($spreadsheet);
            $writer->save('php://output');
        }, $fileName, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => "attachment; filename=\"{$fileName}\"",
            'Cache-Control' => 'max-age=0',
        ]);
    }

    public function downloadTemplate(string $type): StreamedResponse
    {
        $type = in_array($type, ['dosen', 'mahasiswa']) ? $type : 'mahasiswa';
        $fileName = "template-import-{$type}.xlsx";

        $spreadsheet = new Spreadsheet;
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Template Import');

        if ($type === 'dosen') {
            $headers = ['NIDN_NIP', 'Nama Lengkap', 'Email Institusi', 'Password'];
            $samples = [
                ['198502022010121002', 'Dr. Hendra Wijaya, M.Kom.', 'hendra@example.test', ''],
                ['199003032015042001', 'Nurul Hidayah, S.Kom., M.T.', 'nurul@example.test', ''],
            ];
        } else {
            $headers = ['NIM', 'Nama Mahasiswa', 'Email Mahasiswa', 'Password', 'Tahun Masuk (Angkatan)'];
            $samples = [
                ['2024011409001', 'Muhammad Zaky Pratama', 'zaky@student.test', '', 2024],
                ['2024011409002', 'Aisyah Putri Rahmadhani', 'aisyah@student.test', '', 2024],
            ];
        }

        $lastCol = $type === 'dosen' ? 'D' : 'E';
        $sheet->fromArray([$headers], null, 'A1');
        $sheet->getStyle("A1:{$lastCol}1")->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['rgb' => '15803D'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
        ]);
        $sheet->getRowDimension(1)->setRowHeight(24);
        $sheet->freezePane('A2');

        $row = 2;
        foreach ($samples as $sample) {
            $sheet->fromArray([$sample], null, "A{$row}");
            // Nomor NIM/NIDN sebagai teks agar tidak dipotong
            $sheet->getCell("A{$row}")->setValueExplicit($sample[0], DataType::TYPE_STRING);
            $sheet->getRowDimension($row)->setRowHeight(20);
            $row++;
        }

        // Set format kolom NIM/NIDN (A) sebagai teks (@) untuk SELURUH kolom termasuk baris kosong
        // agar angka panjang seperti NIP/NIM tidak dipotong/dibulatkan oleh Excel (max 15 digit angka)
        $sheet->getStyle('A2:A1000')->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_TEXT);

        $lastRow = $row - 1;
        $sheet->getStyle("A1:{$lastCol}{$lastRow}")->applyFromArray([
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['rgb' => 'D1D5DB'],
                ],
            ],
        ]);

        $colsList = $type === 'dosen' ? ['A', 'B', 'C', 'D'] : ['A', 'B', 'C', 'D', 'E'];
        foreach ($colsList as $col) {
            $sheet->getColumnDimension($col)->setAutoSize(true);
        }

        return response()->streamDownload(function () use ($spreadsheet) {
            $writer = new Xlsx($spreadsheet);
            $writer->save('php://output');
        }, $fileName, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => "attachment; filename=\"{$fileName}\"",
            'Cache-Control' => 'max-age=0',
        ]);
    }

    public function import(Request $request): RedirectResponse
    {
        $request->validate([
            'prodi_id' => ['required', 'exists:prodis,id'],
            'role_type' => ['required', Rule::in(['dosen', 'mahasiswa'])],
            'file' => ['required', 'file', 'mimes:csv,txt,xlsx,xls', 'max:4096'],
        ], [
            'file.required' => 'Pilih file Excel yang akan diimpor.',
            'file.mimes' => 'File yang diunggah harus berformat Excel (.xlsx, .xls) atau CSV.',
        ]);

        $prodiId = $request->integer('prodi_id');

        // Pastikan admin hanya bisa import ke prodinya sendiri
        $this->assertProdiScope($prodiId);
        $roleType = $request->input('role_type');
        $roleName = $roleType === 'dosen' ? Role::DOSEN : Role::MAHASISWA;
        $role = Role::where('name', $roleName)->firstOrFail();

        $uploadedFile = $request->file('file');
        $extension = strtolower($uploadedFile->getClientOriginalExtension());

        // Parsing baris data: support xlsx/xls dan csv/txt
        $rows = [];
        if (in_array($extension, ['xlsx', 'xls'])) {
            $spreadsheet = IOFactory::load($uploadedFile->getRealPath());
            $sheet = $spreadsheet->getActiveSheet();
            foreach ($sheet->getRowIterator(2) as $row) {
                $cellIter = $row->getCellIterator();
                $cellIter->setIterateOnlyExistingCells(false);
                $cols = [];
                foreach ($cellIter as $cell) {
                    $cols[] = trim((string) $cell->getValue());
                }
                if (array_filter($cols) === []) {
                    continue;
                }
                $rows[] = $cols;
            }
        } else {
            $raw = file_get_contents($uploadedFile->getRealPath());
            $clean = preg_replace('/^\xEF\xBB\xBF/', '', $raw);
            $lines = preg_split('/\r\n|\r|\n/', trim($clean));
            if (! empty($lines) && count($lines) >= 2) {
                $headerLine = $lines[0];
                $delimiter = str_contains($headerLine, "\t") ? "\t" : (str_contains($headerLine, ';') ? ';' : ',');
                for ($i = 1; $i < count($lines); $i++) {
                    $line = trim($lines[$i]);
                    if ($line === '' || str_starts_with($line, '#')) {
                        continue;
                    }
                    $rows[] = array_map('trim', str_getcsv($line, $delimiter, '"', '\\'));
                }
            }
        }

        if (empty($rows)) {
            return back()->withErrors(['file' => 'File Excel kosong atau tidak berisi baris data.']);
        }

        $successCount = 0;
        $skippedCount = 0;
        $errors = [];
        $temporaryCredentials = [];

        DB::transaction(function () use ($rows, $prodiId, $role, $roleType, &$successCount, &$skippedCount, &$errors, &$temporaryCredentials) {
            foreach ($rows as $idx => $cols) {
                $rowNum = $idx + 2; // +2: baris 1 adalah header, index 0 = baris data ke-2

                $idNum = isset($cols[0]) ? trim($cols[0], "'\"\t\n\r\0\x0B ") : '';
                $name = isset($cols[1]) ? trim($cols[1], "'\"\t\n\r\0\x0B ") : '';
                $email = isset($cols[2]) ? trim($cols[2], "'\"\t\n\r\0\x0B ") : '';
                $pass = (isset($cols[3]) && trim($cols[3]) !== '') ? trim($cols[3]) : null;

                if ($idNum === '' || $name === '' || $email === '') {
                    $skippedCount++;
                    $errors[] = "Baris {$rowNum}: Kolom nomor identitas, nama, atau email tidak boleh kosong.";

                    continue;
                }

                if (! Validator::make(['email' => $email], ['email' => 'required|email'])->passes()) {
                    $skippedCount++;
                    $errors[] = "Baris {$rowNum}: Format email '{$email}' tidak valid.";

                    continue;
                }

                if ($pass !== null && strlen($pass) < 8) {
                    $skippedCount++;
                    $errors[] = "Baris {$rowNum}: Password harus minimal 8 karakter jika diisi.";

                    continue;
                }

                $autoGenerated = ($pass === null);
                $pass = $autoGenerated ? $idNum : $pass;

                $exists = User::where('email', strtolower($email))
                    ->orWhere('nim_nidn', $idNum)
                    ->exists();

                if ($exists) {
                    $skippedCount++;
                    $errors[] = "Baris {$rowNum}: Nomor '{$idNum}' atau email '{$email}' sudah terdaftar dalam sistem.";

                    continue;
                }

                $angkatan = null;
                if ($roleType === 'mahasiswa') {
                    if (isset($cols[4]) && is_numeric(trim($cols[4]))) {
                        $angkatan = (int) trim($cols[4]);
                    }
                    if (! $angkatan) {
                        if (preg_match('/^(20\d{2})/', $idNum, $matches)) {
                            $angkatan = (int) $matches[1];
                        } elseif (preg_match('/^(\d{2})/', $idNum, $matches)) {
                            $two = (int) $matches[1];
                            if ($two >= 18 && $two <= 35) {
                                $angkatan = 2000 + $two;
                            }
                        }
                        if (! $angkatan) {
                            $activeSem = Semester::where('is_active', true)->first();
                            if ($activeSem && ! empty($activeSem->academic_year)) {
                                $angkatan = (int) explode('/', $activeSem->academic_year)[0];
                            } else {
                                $angkatan = (int) date('Y');
                            }
                        }
                    }
                }

                $createdUser = User::create([
                    'name' => $name,
                    'email' => strtolower($email),
                    'nim_nidn' => $idNum,
                    'angkatan' => $angkatan,
                    'prodi_id' => $prodiId,
                    'role_id' => $role->id,
                    'password' => Hash::make($pass),
                    'must_change_password' => true,
                    'email_verified_at' => now(),
                ]);
                $createdUser->roles()->sync([$role->id]);

                if ($autoGenerated) {
                    $temporaryCredentials[] = [
                        'identity' => $idNum,
                        'email' => strtolower($email),
                        'password' => $pass,
                    ];
                }

                $successCount++;
            }
        });
        $typeLabel = $roleType === 'dosen' ? 'Dosen' : 'Mahasiswa';
        $msg = "Impor data {$typeLabel} selesai: {$successCount} berhasil ditambahkan.";
        if ($skippedCount > 0) {
            $msg .= " ({$skippedCount} baris diabaikan/duplikat).";
        }

        return redirect()->route('admin-prodi.users.index', ['prodi_id' => $prodiId, 'tab' => $roleType])
            ->with('notice', $msg)
            ->with('import_errors', $errors)
            ->with('temporary_credentials', $temporaryCredentials);
    }

    private function assertManageableUser(User $user): void
    {
        // Metode ini dipertahankan untuk kompatibilitas;
        // gunakan assertUserScope() untuk pengecekan lengkap dengan scope prodi.
        abort_unless(
            $user->hasRole(Role::DOSEN) || $user->hasRole(Role::MAHASISWA),
            404,
            'Pengguna tidak termasuk lingkup pengelolaan Admin Program Studi.'
        );
    }
}
