<?php

namespace App\Support;

class AdminPreview
{
    public static function users(): array
    {
        return session('admin.users', [
            1 => ['id' => 1, 'name' => 'Ahmad Maulana', 'email' => 'ahmad.maulana@student.test', 'number' => '231011401234', 'role' => 'mahasiswa', 'status' => 'aktif'],
            2 => ['id' => 2, 'name' => 'Budi Santoso, M.Kom.', 'email' => 'budi@example.test', 'number' => '198501012010121001', 'role' => 'dosen', 'status' => 'aktif'],
            3 => ['id' => 3, 'name' => 'Admin Sistem Akademik', 'email' => 'admin@example.test', 'number' => 'ADM001', 'role' => 'admin', 'status' => 'aktif'],
            4 => ['id' => 4, 'name' => 'Admin Prodi TI', 'email' => 'adminprodi@example.test', 'number' => 'AP001', 'role' => 'admin_prodi', 'status' => 'aktif'],
            5 => ['id' => 5, 'name' => 'Dr. H. Kaprodi, M.T.', 'email' => 'kaprodi@example.test', 'number' => '197501012000031001', 'role' => 'kaprodi', 'status' => 'aktif'],
        ]);
    }

    public static function academic(): array
    {
        $default = [
            1 => ['id' => 1, 'type' => 'fakultas', 'code' => 'FIK', 'name' => 'Fakultas Ilmu Komputer', 'parent' => null, 'course' => null, 'students' => [], 'status' => 'aktif'],
            2 => ['id' => 2, 'type' => 'prodi', 'code' => 'IF', 'name' => 'Teknik Informatika', 'parent' => 1, 'course' => null, 'students' => [], 'status' => 'aktif'],
            3 => ['id' => 3, 'type' => 'semester', 'code' => '2026-1', 'name' => 'Ganjil 2026/2027', 'parent' => null, 'course' => null, 'students' => [], 'status' => 'aktif'],
            4 => ['id' => 4, 'type' => 'fakultas', 'code' => 'FT', 'name' => 'Fakultas Teknik', 'parent' => null, 'course' => null, 'students' => [], 'status' => 'aktif'],
            5 => ['id' => 5, 'type' => 'fakultas', 'code' => 'FEB', 'name' => 'Fakultas Ekonomi & Bisnis', 'parent' => null, 'course' => null, 'students' => [], 'status' => 'aktif'],
        ];

        $academic = session('admin.academic', $default);
        $filtered = array_filter($academic, fn ($record) => in_array($record['type'] ?? '', ['fakultas', 'prodi', 'semester']));
        if (count($filtered) !== count($academic)) {
            session(['admin.academic' => $filtered]);
        }

        return $filtered;
    }

    public static function log(string $action): void
    {
        $logs = session('admin.logs', []);
        array_unshift($logs, ['time' => now()->format('d M Y, H:i:s'), 'actor' => 'Admin Akademik', 'action' => $action]);
        session(['admin.logs' => array_slice($logs, 0, 100)]);
    }

    /**
     * 3 Fakultas, masing-masing memiliki 4 Program Studi (Total 12 Prodi).
     */
    public static function facultyProdiData(): array
    {
        return [
            'FIK' => [
                'id' => 1,
                'code' => 'FIK',
                'name' => 'Fakultas Ilmu Komputer',
                'dekan' => 'Prof. Dr. Ir. H. M. Zain, M.Kom.',
                'wakil' => 'Dr. Eng. Rina Marlina, M.Kom.',
                'students_count' => 420,
                'prodis_count' => 4,
                'status' => 'Aktif',
                'prodis' => [
                    'IF' => [
                        'id' => 101,
                        'code' => 'IF',
                        'name' => 'S1 Teknik Informatika',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FIK',
                        'faculty_name' => 'Fakultas Ilmu Komputer',
                        'kaprodi' => 'Dr. H. Kaprodi, M.T.',
                        'wakil' => 'Dr. Budi Santoso, M.Kom.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 125,
                        'avg_ipk' => '3,58',
                        'courses_count' => 8,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'IF101', 'name' => 'Algoritma & Pemrograman', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'IF-A'],
                            ['code' => 'IF102', 'name' => 'Struktur Data & Analisis Algoritma', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'IF-A'],
                            ['code' => 'IF201', 'name' => 'Basis Data Relasional & NoSQL', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'IF-B'],
                            ['code' => 'IF202', 'name' => 'Pemrograman Berorientasi Objek (OOP)', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'IF-A'],
                            ['code' => 'IF301', 'name' => 'Kecerdasan Buatan & Machine Learning', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'IF-A'],
                            ['code' => 'IF302', 'name' => 'Rekayasa Perangkat Lunak Terapan', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'IF-C'],
                            ['code' => 'IF401', 'name' => 'Jaringan Komputer & Keamanan Siber', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'IF-B'],
                            ['code' => 'IF402', 'name' => 'Tugas Akhir / Skripsi', 'sks' => 6, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'IF-A'],
                        ],
                    ],
                    'SI' => [
                        'id' => 102,
                        'code' => 'SI',
                        'name' => 'S1 Sistem Informasi',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FIK',
                        'faculty_name' => 'Fakultas Ilmu Komputer',
                        'kaprodi' => 'Dr. Ahmad Fauzi, M.Kom.',
                        'wakil' => 'Nurul Hidayah, M.T.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 110,
                        'avg_ipk' => '3,52',
                        'courses_count' => 8,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'SI101', 'name' => 'Pengantar Sistem Informasi Bisnis', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SI-A'],
                            ['code' => 'SI102', 'name' => 'Analisis & Perancangan Sistem', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SI-A'],
                            ['code' => 'SI201', 'name' => 'Enterprise Architecture (EA)', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SI-B'],
                            ['code' => 'SI202', 'name' => 'Manajemen Proyek Teknologi Informasi', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SI-A'],
                            ['code' => 'SI301', 'name' => 'Audit & Tata Kelola SI', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SI-B'],
                            ['code' => 'SI302', 'name' => 'E-Business & Digital Commerce', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SI-A'],
                            ['code' => 'SI401', 'name' => 'Customer Relationship Management', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SI-A'],
                            ['code' => 'SI402', 'name' => 'Skripsi / Tugas Akhir', 'sks' => 6, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SI-A'],
                        ],
                    ],
                    'TI' => [
                        'id' => 103,
                        'code' => 'TI',
                        'name' => 'S1 Teknologi Informasi',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FIK',
                        'faculty_name' => 'Fakultas Ilmu Komputer',
                        'kaprodi' => 'Dr. Eng. Farhan Ramadhan, M.T.',
                        'wakil' => 'Hendra Pratama, M.Cs.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 95,
                        'avg_ipk' => '3,46',
                        'courses_count' => 7,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'TI101', 'name' => 'Infrastruktur TI & Komputasi Awan', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TI-A'],
                            ['code' => 'TI102', 'name' => 'Keamanan Siber & Kriptografi', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TI-A'],
                            ['code' => 'TI201', 'name' => 'Integrasi Sistem Terdistribusi', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TI-B'],
                            ['code' => 'TI202', 'name' => 'Internet of Things (IoT)', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TI-A'],
                            ['code' => 'TI301', 'name' => 'DevOps & Otomasi Sistem', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TI-A'],
                            ['code' => 'TI302', 'name' => 'Tata Kelola TI (COBIT & ITIL)', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TI-B'],
                            ['code' => 'TI401', 'name' => 'Forensik Digital & Investigasi Siber', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TI-A'],
                        ],
                    ],
                    'SD' => [
                        'id' => 104,
                        'code' => 'SD',
                        'name' => 'S1 Sains Data',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FIK',
                        'faculty_name' => 'Fakultas Ilmu Komputer',
                        'kaprodi' => 'Dr. Ratna Dewi, M.Sc.',
                        'wakil' => 'Faisal Akbar, M.Stat.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 90,
                        'avg_ipk' => '3,62',
                        'courses_count' => 7,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'SD101', 'name' => 'Pengantar Sains Data & Pemrograman Python', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SD-A'],
                            ['code' => 'SD102', 'name' => 'Statistika Multivariat untuk Data Science', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SD-A'],
                            ['code' => 'SD201', 'name' => 'Pemrosesan Data Skala Besar (Big Data)', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SD-B'],
                            ['code' => 'SD202', 'name' => 'Pembelajaran Mesin Terapan (Machine Learning)', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SD-A'],
                            ['code' => 'SD301', 'name' => 'Pemrosesan Bahasa Alami (NLP)', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SD-A'],
                            ['code' => 'SD302', 'name' => 'Visualisasi Data Interaktif & Dashboarding', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SD-B'],
                            ['code' => 'SD401', 'name' => 'Deep Learning & Visi Komputer', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'SD-A'],
                        ],
                    ],
                ],
            ],
            'FT' => [
                'id' => 2,
                'code' => 'FT',
                'name' => 'Fakultas Teknik',
                'dekan' => 'Prof. Dr. Ir. Bambang Suhardi, M.T.',
                'wakil' => 'Dr. Ir. Wahyu Wibowo, M.T.',
                'students_count' => 460,
                'prodis_count' => 4,
                'status' => 'Aktif',
                'prodis' => [
                    'TE' => [
                        'id' => 201,
                        'code' => 'TE',
                        'name' => 'S1 Teknik Elektro',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FT',
                        'faculty_name' => 'Fakultas Teknik',
                        'kaprodi' => 'Dr. Ir. Suryadi, M.T.',
                        'wakil' => 'Agus Purnomo, M.T.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 120,
                        'avg_ipk' => '3,41',
                        'courses_count' => 8,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'TE101', 'name' => 'Analisis Rangkaian Listrik', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TE-A'],
                            ['code' => 'TE102', 'name' => 'Sistem Tenaga Listrik', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TE-A'],
                            ['code' => 'TE201', 'name' => 'Dasar Sistem Telekomunikasi', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TE-B'],
                            ['code' => 'TE202', 'name' => 'Sistem Kendali Kontinu & Otomasi', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TE-A'],
                            ['code' => 'TE301', 'name' => 'Elektronika Daya Terapan', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TE-A'],
                            ['code' => 'TE302', 'name' => 'Mikroprosesor & Embedded System', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TE-B'],
                            ['code' => 'TE401', 'name' => 'Energi Terbarukan & Smart Grid', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TE-A'],
                            ['code' => 'TE402', 'name' => 'Skripsi / Proyek Akhir', 'sks' => 6, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TE-A'],
                        ],
                    ],
                    'TIN' => [
                        'id' => 202,
                        'code' => 'TIN',
                        'name' => 'S1 Teknik Industri',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FT',
                        'faculty_name' => 'Fakultas Teknik',
                        'kaprodi' => 'Dr. H. Triyono, S.T., M.T.',
                        'wakil' => 'Dewi Lestari, M.T.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 130,
                        'avg_ipk' => '3,48',
                        'courses_count' => 8,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'TI101', 'name' => 'Pengantar Teknik Industri & Etika', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TIN-A'],
                            ['code' => 'TI102', 'name' => 'Ergonomi & Perancangan Sistem Kerja', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TIN-A'],
                            ['code' => 'TI201', 'name' => 'Penelitian Operasional (OR)', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TIN-B'],
                            ['code' => 'TI202', 'name' => 'Perencanaan & Pengendalian Produksi', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TIN-A'],
                            ['code' => 'TI301', 'name' => 'Tata Letak Fasilitas & Pabrik', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TIN-B'],
                            ['code' => 'TI302', 'name' => 'Manajemen Rantai Pasok (SCM)', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TIN-A'],
                            ['code' => 'TI401', 'name' => 'Pengendalian & Penjaminan Mutu', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TIN-A'],
                            ['code' => 'TI402', 'name' => 'Tugas Akhir Perancangan Pabrik', 'sks' => 6, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TIN-A'],
                        ],
                    ],
                    'TM' => [
                        'id' => 203,
                        'code' => 'TM',
                        'name' => 'S1 Teknik Mesin',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FT',
                        'faculty_name' => 'Fakultas Teknik',
                        'kaprodi' => 'Dr. Ir. Joko Pramono, M.T.',
                        'wakil' => 'Bambang Hariyadi, M.Eng.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 110,
                        'avg_ipk' => '3,35',
                        'courses_count' => 7,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'TM101', 'name' => 'Statika Struktur & Mekanika Bahan', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TM-A'],
                            ['code' => 'TM102', 'name' => 'Termodinamika Teknik', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TM-A'],
                            ['code' => 'TM201', 'name' => 'Mekanika Fluida & Hidrolika', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TM-B'],
                            ['code' => 'TM202', 'name' => 'Kinematika & Dinamika Permesinan', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TM-A'],
                            ['code' => 'TM301', 'name' => 'Perpindahan Kalor & Massa', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TM-A'],
                            ['code' => 'TM302', 'name' => 'Elemen Mesin & Perancangan CAD', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TM-B'],
                            ['code' => 'TM401', 'name' => 'Teknologi Manufaktur & CNC', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TM-A'],
                        ],
                    ],
                    'TS' => [
                        'id' => 204,
                        'code' => 'TS',
                        'name' => 'S1 Teknik Sipil',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FT',
                        'faculty_name' => 'Fakultas Teknik',
                        'kaprodi' => 'Dr. Ir. Kusuma Wardani, M.T.',
                        'wakil' => 'Rifki Prasetya, M.T.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 100,
                        'avg_ipk' => '3,44',
                        'courses_count' => 7,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'TS101', 'name' => 'Mekanika Rekayasa', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TS-A'],
                            ['code' => 'TS102', 'name' => 'Teknologi Bahan Konstruksi', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TS-A'],
                            ['code' => 'TS201', 'name' => 'Mekanika Tanah & Pondasi', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TS-B'],
                            ['code' => 'TS202', 'name' => 'Rekayasa Struktur Beton Bertulang', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TS-A'],
                            ['code' => 'TS301', 'name' => 'Hidrologi & Pengelolaan Sumber Daya Air', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TS-B'],
                            ['code' => 'TS302', 'name' => 'Teknik Transportasi & Perkerasan Jalan', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TS-A'],
                            ['code' => 'TS401', 'name' => 'Manajemen Konstruksi & Biaya Proyek', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'TS-A'],
                        ],
                    ],
                ],
            ],
            'FEB' => [
                'id' => 3,
                'code' => 'FEB',
                'name' => 'Fakultas Ekonomi & Bisnis',
                'dekan' => 'Prof. Dr. Dra. Hj. Sri Rahayu, M.M.',
                'wakil' => 'Dr. Hendra Gunawan, S.E., M.Si.',
                'students_count' => 510,
                'prodis_count' => 4,
                'status' => 'Aktif',
                'prodis' => [
                    'MNJ' => [
                        'id' => 301,
                        'code' => 'MNJ',
                        'name' => 'S1 Manajemen',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FEB',
                        'faculty_name' => 'Fakultas Ekonomi & Bisnis',
                        'kaprodi' => 'Dr. H. Ruslan Effendi, M.M.',
                        'wakil' => 'Siti Aminah, S.E., M.M.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 160,
                        'avg_ipk' => '3,55',
                        'courses_count' => 8,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'MN101', 'name' => 'Pengantar Manajemen & Bisnis', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'MNJ-A'],
                            ['code' => 'MN102', 'name' => 'Manajemen Pemasaran Modern', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'MNJ-A'],
                            ['code' => 'MN201', 'name' => 'Manajemen Keuangan Korporat', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'MNJ-B'],
                            ['code' => 'MN202', 'name' => 'Manajemen Sumber Daya Manusia', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'MNJ-A'],
                            ['code' => 'MN301', 'name' => 'Manajemen Operasional & Strategik', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'MNJ-B'],
                            ['code' => 'MN302', 'name' => 'Kewirausahaan & Business Plan', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'MNJ-A'],
                            ['code' => 'MN401', 'name' => 'Manajemen Risiko & Keberlanjutan Bisnis', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'MNJ-A'],
                            ['code' => 'MN402', 'name' => 'Skripsi Manajemen', 'sks' => 6, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'MNJ-A'],
                        ],
                    ],
                    'AKT' => [
                        'id' => 302,
                        'code' => 'AKT',
                        'name' => 'S1 Akuntansi',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FEB',
                        'faculty_name' => 'Fakultas Ekonomi & Bisnis',
                        'kaprodi' => 'Dr. Yuliana Sari, S.E., Ak., M.Ak.',
                        'wakil' => 'Aditia Pratama, M.Ak.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 140,
                        'avg_ipk' => '3,60',
                        'courses_count' => 8,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'AK101', 'name' => 'Pengantar Akuntansi Keuangan', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'AKT-A'],
                            ['code' => 'AK102', 'name' => 'Akuntansi Biaya & Penentuan Harga', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'AKT-A'],
                            ['code' => 'AK201', 'name' => 'Akuntansi Keuangan Menengah', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'AKT-B'],
                            ['code' => 'AK202', 'name' => 'Perpajakan & Hukum Pajak Indonesia', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'AKT-A'],
                            ['code' => 'AK301', 'name' => 'Pengauditan & Jasa Asurans', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'AKT-A'],
                            ['code' => 'AK302', 'name' => 'Sistem Informasi Akuntansi (SIA)', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'AKT-B'],
                            ['code' => 'AK401', 'name' => 'Akuntansi Sektor Publik', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'AKT-A'],
                            ['code' => 'AK402', 'name' => 'Skripsi Akuntansi', 'sks' => 6, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'AKT-A'],
                        ],
                    ],
                    'EP' => [
                        'id' => 303,
                        'code' => 'EP',
                        'name' => 'S1 Ekonomi Pembangunan',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FEB',
                        'faculty_name' => 'Fakultas Ekonomi & Bisnis',
                        'kaprodi' => 'Dr. Ridwan Santoso, M.Ec.',
                        'wakil' => 'Indah Permatasari, M.Si.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 110,
                        'avg_ipk' => '3,49',
                        'courses_count' => 7,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'EP101', 'name' => 'Pengantar Teori Ekonomi Mikro', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'EP-A'],
                            ['code' => 'EP102', 'name' => 'Pengantar Teori Ekonomi Makro', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'EP-A'],
                            ['code' => 'EP201', 'name' => 'Matematika & Statistika Ekonomi Terapan', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'EP-B'],
                            ['code' => 'EP202', 'name' => 'Ekonometrika Dasar & Analisis Regresi', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'EP-A'],
                            ['code' => 'EP301', 'name' => 'Ekonomi Pembangunan Daerah & Regional', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'EP-B'],
                            ['code' => 'EP302', 'name' => 'Ekonomi Moneter & Kebijakan Bank Sentral', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'EP-A'],
                            ['code' => 'EP401', 'name' => 'Kebijakan Fiskal & APBN', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'EP-A'],
                        ],
                    ],
                    'BD' => [
                        'id' => 304,
                        'code' => 'BD',
                        'name' => 'S1 Bisnis Digital',
                        'jenjang' => 'S1',
                        'faculty_code' => 'FEB',
                        'faculty_name' => 'Fakultas Ekonomi & Bisnis',
                        'kaprodi' => 'Dr. Maya Anggraini, S.T., M.M.',
                        'wakil' => 'Rangga Yudha, M.B.A.',
                        'semester' => 'Semester Ganjil 2026/2027',
                        'students_count' => 100,
                        'avg_ipk' => '3,65',
                        'courses_count' => 7,
                        'status' => 'Aktif',
                        'courses' => [
                            ['code' => 'BD101', 'name' => 'Fundamental Bisnis Digital & Start-up', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'BD-A'],
                            ['code' => 'BD102', 'name' => 'Digital Marketing & Content Strategy', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'BD-A'],
                            ['code' => 'BD201', 'name' => 'Teknologi Finansial (Fintech)', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'BD-B'],
                            ['code' => 'BD202', 'name' => 'Customer Data Analytics & Business Intelligence', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'BD-A'],
                            ['code' => 'BD301', 'name' => 'Platform E-Commerce & Marketplace', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'BD-A'],
                            ['code' => 'BD302', 'name' => 'Inovasi Produk & Desain UX Bisnis', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'BD-B'],
                            ['code' => 'BD401', 'name' => 'Hukum, Etika & Regulasi Bisnis Digital', 'sks' => 3, 'semester' => 'Semester Ganjil 2026/2027', 'kelas' => 'BD-A'],
                        ],
                    ],
                ],
            ],
        ];
    }
}
