<form method="get" action="{{ route('admin.page', 'monitoring') }}" class="flex flex-wrap items-end gap-3">
    <input type="hidden" name="detail" value="{{ $detail }}">
    <input type="hidden" name="contoh" value="{{ $demo ? 1 : 0 }}">
    <div><label for="monitor-range" class="mb-1 block text-xs font-semibold text-muted">{{ $detail === 'ai' ? 'Tampilan' : 'Waktu' }}</label><select id="monitor-range" name="rentang" class="field" onchange="const form = this.form; const custom = this.value === 'custom'; const monthly = this.value === 'monthly'; form.querySelector('[data-month]').hidden = !monthly; form.querySelector('[data-dates]').hidden = !custom; if (!custom && !monthly) form.requestSubmit();">@foreach($rangeData['choices'] as $value => $label)<option value="{{ $value }}" @selected($rangeData['range'] === $value)>{{ $label }}</option>@endforeach</select></div>
    <div data-month @if($rangeData['range'] !== 'monthly') hidden @endif><label for="monitor-month" class="mb-1 block text-xs font-semibold text-muted">Bulan</label><input id="monitor-month" type="month" name="bulan" class="field" max="{{ now()->format('Y-m') }}" value="{{ $rangeData['month']->format('Y-m') }}"></div>
    <div data-dates @if($rangeData['range'] !== 'custom') hidden @endif><div class="flex flex-wrap gap-3"><div><label for="monitor-from" class="mb-1 block text-xs font-semibold text-muted">Dari</label><input id="monitor-from" type="date" name="mulai" class="field" max="{{ now()->toDateString() }}" value="{{ $rangeData['from']->toDateString() }}"></div><div><label for="monitor-to" class="mb-1 block text-xs font-semibold text-muted">Sampai</label><input id="monitor-to" type="date" name="akhir" class="field" max="{{ now()->toDateString() }}" value="{{ $rangeData['to']->toDateString() }}"></div></div></div>
    @if($detail === 'ai' && $rangeData['range'] !== 'requests')<div><label for="monitor-metric" class="mb-1 block text-xs font-semibold text-muted">Pemakaian</label><select id="monitor-metric" name="metrik" class="field" onchange="this.form.requestSubmit()"><option value="token" @selected($metric === 'token')>Token</option><option value="permintaan" @selected($metric === 'permintaan')>Permintaan</option></select></div>@endif
    <button class="button-secondary" type="submit">Tampilkan</button>
</form>
@unless(($detail === 'server' && $rangeData['range'] === 'realtime') || $rangeData['range'] === 'requests')
<p class="mt-3 text-xs text-muted">{{ $rangeData['caption'] }} ({{ $rangeData['granularity'] }})</p>
@endunless
@if($rangeData['notice'])<p role="alert" class="mt-2 text-sm text-brand-dark">{{ $rangeData['notice'] }}</p>@endif
@if($rangeData['range'] === 'realtime')<p role="status" class="mt-3 rounded-lg bg-brand-soft px-3 py-2 text-xs leading-5 text-brand-dark">{{ $detail === 'server' ? ($demo ? 'Pratinjau realtime dengan data simulasi. Batang RAM dan CPU berubah otomatis setiap 3 detik.' : 'Realtime belum terhubung. Pemakaian RAM dan CPU akan tersedia setelah pengukuran server aktif.') : ($demo ? 'Pratinjau realtime dengan data simulasi. Pilih Tampilkan untuk memperbarui jendela waktu.' : 'Realtime belum terhubung. Data langsung akan tersedia setelah pencatatan pengunjung dan pengukuran server diaktifkan.') }}</p>@endif
